name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Cambia la versión si es necesario

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint  # Omitir si no quieres verificar el código

      - name: Build TypeScript
        run: npm run build  # Ejecuta la compilación del proyecto

      - name: Run tests
        run: npm test  # Ejecuta las pruebas con Jest
